@auth = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoxLCJpYXQiOjE3NDA3MzQ4MzMsImV4cCI6MTc0MDc0NTYzM30.JGGNIS1xvv31_xWccmS58nGQyxIsu5McnmY4AZ5I--E

### 导入用户数据

GET http://localhost:3001/user/init_db

### 登录
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123123"
}

### 获取好友列表
# @name add_friend
POST http://localhost:3001/friendship/add/friend/3
Authorization: bearer {{auth}}

### 获取好友列表
# @name friendship
GET http://localhost:3001/friendship
Authorization: bearer {{auth}}
### 创建单聊
GET http://localhost:3001/chatroom/create-one-to-one?friendId=3
Authorization: bearer {{auth}}

### 创建群聊
GET http://localhost:3001/chatroom/create-group
Authorization: bearer {{auth}}

### 获取聊天室信息
GET http://localhost:3001/chatroom
Authorization: bearer {{auth}}

### 群聊添加成员
POST http://localhost:3001/chatroom/2/add_member/3
Authorization: bearer {{auth}}