### 导入用户数据

GET http://localhost:3001/user/init_db

### 登录
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123123"
}

### 获取好友列表
GET http://localhost:3001/friendship/list
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoxLCJpYXQiOjE3NDAzOTE5OTksImV4cCI6MTc0MDM5NTU5OX0.s5CR3VkFbNsNmz44K8EDM0DcWzTLpIPC55BJhNnMD_U